# Generated by Django 5.0.6 on 2025-03-31 13:41

import django.core.validators
import django.db.models.deletion
import products.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='SLUG')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='SLUG')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_active', models.BooleanField(default=False, verbose_name='Публикация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title', 'price', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d/', validators=[products.validators.image_resolution_validator, products.validators.image_size_validator], verbose_name='Изображение')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение к продукту',
                'verbose_name_plural': 'Изображения к продукту',
            },
        ),
    ]
