# Generated by Django 5.0.6 on 2025-04-08 14:07

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images/%Y/%m/%d/', validators=[products.validators.image_resolution_validator, products.validators.image_size_validator], verbose_name='Обложка'),
            preserve_default=False,
        ),
    ]
